### ISSUE TITLE
Python Branch - Randomly stops working

### ISSUE THREAD

**Issue by stevesbrain** [jreese/znc-push#165] opened 2015-06-09 10:50 UTC
Hey folks,

Quick question. I've moved to the python branch given that it will be the actively developed branch. However, whilst it works well when it's working, I've noticed that it will randomly "die" without any form of notification.

I will notice I haven't received any push's for a while, so I'll try doing a: 
```
/msg *push send test
```

It won't do anything at all. No query with *push opens up, nor does any form of failure message. I then to a:

```
/msg *status reloadmod push
```

To which it says "ok", and a subsequent test of *push works successfully. Is there any way to debug this? Somewhere it keeps logs, a flag to start it in debug mode, etc? Many thanks.

**Comment by dgw** [comment] 2015-06-09 11:17
Duplicate of #116. Possibly related to #164?

**Comment by stevesbrain** [comment] 2015-06-09 11:29
Ah, my apologies, thanks!

**Closed** 2015-09-21 21:39 UTC
