### ISSUE TITLE
Won't compile on ZNC 1.6.1

### ISSUE THREAD

**Issue by DangerDane** [jreese/znc-push#174] opened 2015-09-20 20:32 UTC
I am getting loads of errors trying to compile the cpp file on ZNC 1.6.1. If needs be I will submit the entire failure log from the compilation.

**Comment by Mikaela** [comment] 2015-09-21 05:12
Use the python module instead, https://github.com/jreese/znc-push/raw/python/push.py as last time I checked the cpp branch wasn't going to get any new features.

@jreese could you change python as the default branch?

**Comment by Mikaela** [comment] 2015-09-21 05:15
Also duplicate of at least https://github.com/jreese/znc-push/issues/143 and https://github.com/jreese/znc-push/issues/141

**Comment by DangerDane** [comment] 2015-09-21 16:37
Well how would I then build Push.py so that it works?. I am only used to working with .so modules.

**Comment by Mikaela** [comment] 2015-09-21 16:43
You don't build python modules, you just drop the .py to either module folder and `/msg *status loadmod push` or check the box at webadmin.

You must load the global modpython module first for Python modules to appear (same with modperl), it's a global module. If you don't have it, recompile ZNC with `--enable-python`or install some package from repos of your distribution, probably `znc-python`or something.

**Comment by jreese** [comment] 2015-09-21 19:02
FWIW, I was able to compile the C module against 1.6.1 without any errors.  There were warnings from some of the ZNC libraries, but nothing that prevented znc-push from building and loading into ZNC.

**Closed by jreese** 2015-09-21 19:02 UTC
